### ISSUE TITLE
SyntaxError: Unexpected token ? in String.prototype.replaceAll ??

### ISSUE THREAD

**Issue by bzhn** [mainarthur/telegram-escape#2]
Hello, I tried to use your module and got a problem.

**Here is my code:**

```JavaScript
const { HTML } = require("telegram-escape");

// Some code...

bot.sendMessage(me, HTML`<a href="${"https://github.com/mainarthur/telegram-escape/issues/new"}">${"Anyword < > & . / word"}</a>`, {parse_mode: 'HTML'});
```

**Here is the error message:**

```
/home/myusername/Documents/MyScripts/myprojectfolder/node_modules/telegram-escape/index.js:2
  String.prototype.replaceAll ??
                               ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<myusername> (/home/myusername/Documents/MyScripts/myprojectfolder/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

*My node version is v10.19.0 and npm version is 6.14.4*

**Comment by mainarthur** [comment]
You can try to update your nodejs version to 14
But I'll add fix on it
